services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend